gcd/urls.py
from django.contrib import admin
from django.urls import path
import web.views as views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('clientes/cadastrar/', views.cliente_cad, name='cliente_cad'),
    path('clientes/lista/', views.cliente_list, name='cliente_list'),
    path('clientes/<cpf>', views.cliente_detail, name='cliente_detail'),
    path('clientes/<cpf>/edit', views.cliente_edit, name='cliente_edit'),
    path('services/cadastrar', views.services_cad, name='services_cad'),
    path('services/lista', views.services_list, name='services_list'),
    path('services/<id>', views.services_detail, name='services_detail'),
    path('services/<id>/edit', views.services_edit, name='services_edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models


class ClienteModel(models.Model):
    sexo_choices = [['Feminino', 'Feminino'], ['Masculino', 'Masculino']]
    data_cadastro = models.DateTimeField('Data de cadastro', auto_now_add=True)

    nome = models.CharField('Nome', max_length=50)
    cpf = models.CharField('CPF', primary_key=True, null=False, max_length=14)
    rg = models.CharField('RG', max_length=20, null=True)
    data_nascimento = models.CharField('Data de nascimento', max_length=10, null=False, default='01/01/1900')
    sexo = models.CharField(max_length=9, choices=sexo_choices, null=True, blank=True)
    
    # Contato

    tel_fixo = models.CharField('Telefone Residencial', max_length=15, blank=True)
    tel_cel = models.CharField('Telefone Celular', max_length=15, blank=True)
    tel_emergency = models.CharField('Telefone Emergência', max_length=15, blank=True)
    email = models.EmailField('E-mail', blank=True)

    # Endereço
    cep = models.CharField('CEP', null=False, blank=False, default='', max_length=9)
    logradouro = models.CharField('Endereço', max_length=100, null=False, default='')
    numero = models.CharField('Número', null=False, max_length=5, blank=False, default=0)
    complemento = models.CharField('Complemento', max_length=30, null=False, blank=True)
    bairro = models.CharField('Bairro', max_length=100, null=False, blank=False, default='')
    cidade = models.CharField('Cidade', max_length=100, null=False, blank=False, default='')
    uf = models.CharField('Estado', max_length=2, null=False, blank=False, default='')
    

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'


class Servicos(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField('Nome', default='', null=False, max_length=50)
    valor = models.FloatField('Valor', null=False, default=0)
    descricao = models.TextField('Descrição', default='', null=False)
    
    
    
    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'

web/forms.py
from django import forms
from .models import ClienteModel, Servicos


class ClienteCadForm(forms.ModelForm):

    class Meta:
        model = ClienteModel
        fields = [
            'nome', 'cpf', 'rg', 'data_nascimento', 'email',
            'tel_fixo', 'sexo', 'logradouro', 'numero', 'complemento',
            'bairro', 'cidade', 'uf', 'tel_cel', 'tel_emergency', 'cep'
            ]


class ServicesForm(forms.ModelForm):

    class Meta:
        model = Servicos
        fields = [
            'nome', 'valor', 'descricao'
        ]
        

web/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ClienteCadForm, ServicesForm
from .models import ClienteModel, Servicos


def index(request):
    return render(request, 'index.html')


def cliente_cad(request):
    page = 'clientes/cliente_cad.html'
    form = ClienteCadForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('cliente_list')

    return render(request, page, {'form': form})


def cliente_edit(request, cpf):
    page = 'clientes/cliente_edit.html'
    cliente = ClienteModel.objects.get(cpf=cpf)
    form = ClienteCadForm(request.POST or None, instance=cliente)
    if request.POST:
        if form.is_valid() and 'salvar' in request.POST:
            form.save()
            return redirect('cliente_list')
        if 'excluir' in request.POST:
            cliente.delete()
            return redirect('cliente_list')

    return render(request, page, {'form': form, 'cliente': cliente})


def cliente_list(request):
    page = 'clientes/cliente_list.html'
    clientes = ClienteModel.objects.all()
    clientes = clientes.order_by('nome')

    return render(request, page, {'clientes': clientes})


def cliente_detail(request, cpf):
    page = 'clientes/cliente_detail.html'
    cliente = ClienteModel.objects.filter(cpf=cpf)

    return render(request, page, {'cliente': cliente})


def services_cad(request):
    page = 'services/services_cad.html'
    form = ServicesForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('services_list')

    return render(request, page, {'form': form})


def services_edit(request, id):
    page = 'services/services_edit.html'
    services = Servicos.objects.get(id=id)
    form = ServicesForm(request.POST or None, instance=services)
    if request.POST:
        if form.is_valid() and 'salvar' in request.POST:
            form.save()
            return redirect('services_list')
        if 'excluir' in request.POST:
            services.delete()
            return redirect('services_list')

    return render(request, page, {'form': form, 'services': services})


def services_list(request):
    page = 'services/services_list.html'
    services = Servicos.objects.all()
    services = services.order_by('nome')

    return render(request, page, {'services': services})


def services_detail(request, id):
    page = 'services/services_detail.html'
    services = Servicos.objects.filter(id=id)

    return render(request, page, {'services': services})

web/templates/clientes/cliente_cad.html
{% extends 'base.html' %}

{% block content %}
<script src="../../static/js/cep.js"></script>
<script src="../../static/js/cpf.js"></script>
<script src="../../static/js/cel.js"></script>
<script src="../../static/js/data.js"></script>
<script src="../../static/js/nome.js"></script>
<br>
<br>
<div class="container-fluid">
  <div class="row">
    <!-- Basic Form-->
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <h3 class="h4">Cadastrar Cliente</h3>
        </div>
        <div class="card-body">
          <p>Os campos com <b>*</b> são de preenchimento obrigatório.</p>
           <!-------------------------------------------------------- DADOS PESSOAIS ------------------------------------------->
           <form name="cliente" method="post">        
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="form-row">

            <div class="form-group col-md-5">
              <label for="id_nome">Nome*</label>
              <input type="text" name="nome" class="form-control" required id="id_nome" placeholder="Nome completo" maxlength="100" onkeyup="capitalize(this.id)">
            </div>
            <div class="form-group col-md-2">      
              <label for="id_cpf">CPF*</label>
              <input type="text" name="cpf" class="form-control" required id="id_cpf" placeholder="CPF" maxlength="14" onblur="validarCPF(this.value)" oninput="mascara(this)">
              {% if form.cpf.errors %}
              <script>
                  alert('CPF já cadastrado!')
              </script>
              {% endif %}
            </div>

            <div class="form-group col-md-2">
              <label for="id_rg">RG*</label>
              <input type="text" name="rg" class="form-control" required id="id_rg" placeholder="RG" max="20">
            </div>

            <div class="form-group col-md-2">
              <label for="id_data_nascimento">Data de nascimento*</label>
              <input type="text" name="data_nascimento" class="form-control" required id="id_data_nascimento" placeholder="01/01/1900" maxlength="10 " onkeypress="mascaraData(this)">
            </div>

            <div class="form-group col-md-1">
               <label for="id_sexo">Sexo</label>
                          <select name="sexo" required id="id_sexo" class="form-control">
                              <option value="Feminino">Feminino</option>
                              <option value="Masculino">Masculino</option>
                              <option value="" selected>---------</option>
                          </select>
            </div>
            <!-- <div class="form-group">
                <label for="id_photo">Foto</label>
                <input type="file" name="photo" class="form-control" id="photo">
                </div> -->
          </div>
                    <!-------------------------------------------------------- FIM DADOS PESSOAIS ------------------------------------------->
                    <hr class="my-3">
                              <!-- ==============================================CONTATOS======================================================= -->
                          <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="id_tel_fixo">Telefone Residencial</label>
                            <input type="text" name="tel_fixo" class="form-control" id="id_tel_fixo" placeholder="Fixo" maxlength="15" onkeydown="mask(this, mtel)">
                            </div>

                        <div class="form-group col-md-2">
                            <label for="id_tel_cel">Telefone Celular</label>
                            <input type="text" name="tel_cel" class="form-control" id="id_tel_cel" placeholder="Celular" maxlength="15" onkeydown="mask(this, mtel)">
                            </div>
                        <div class="form-group col-md-2">
                            <label for="id_tel_cel">Telefone Emergência</label>
                            <input type="text" name="tel_emergency" class="form-control" id="id_tel_emergency" placeholder="Emergência" maxlength="15" onkeydown="mask(this, mtel)">
                            </div> 
                        <div class="form-group col-md-4">
                          <label for="id_email">E-mail</label>
                          <input type="text" name="email" class="form-control" id="email" placeholder="E-mail">
                          </div>
                          </div>
                        
                        <!-------------------------------------------------------- FIM CONTATOS ------------------------------------------->

                        <hr class="my-3">
                          <!-------------------------------------------------------- ENDEREÇO ------------------------------------------->
                          <div class="form-row">
                        <div class="form-group col-md-2">
                          <label for="id_cep">CEP*</label>
                          <input type="text" name="cep" class="form-control" required id="id_cep" placeholder="CEP" maxlength="9" onblur="pesquisacep(this.value)">
                        </div>
                        <div class="form-group col-md-6">
                          <label for="id_logradouro">Endereço*</label>
                          <input type="text" name="logradouro" class="form-control" required id="id_logradouro" placeholder="Rua dos Bobos" maxlength="100">
                        </div>
                        <div class="form-group col-md-1">
                                <label for="id_numero">Número*</label>
                                <input type="text" name="numero" class="form-control" required id="id_numero" placeholder="Nº" maxlength="5">
                              </div>
                        <div class="form-group col-md-3">
                            <label for="id_complemento">Complemento</label>
                            <input type="text" name="complemento" class="form-control" id="id_complemento" placeholder="Bloco, Apartamento" maxlength="30">
                            </div> 
                      
                          <div class="form-group col-md-4">
                            <label for="id_bairro">Bairro*</label>
                            <input type="text" name="bairro" class="form-control" required id="id_bairro" placeholder="Bairro" maxlength="100">
                          </div>     
                        
                          <div class="form-group col-md-4">
                            <label for="id_cidade">Cidade*</label>
                            <input type="text" name="cidade" class="form-control" required id="id_cidade" placeholder="Cidade" maxlength="100">
                          </div>
                          <div class="form-group col-md-1">
                                <label for="id_uf">Estado*</label>
                                <input type="text" name="uf" class="form-control" required id="id_uf" placeholder="UF" maxlength="2">
                              </div>
                              
                          <!--------------------------------------------------------FIM DO ENDEREÇO ------------------------------------------->
                        </div>                        
                        <hr class="my-3">

                <div class="pure-controls">
                    <button type="submit" class="btn btn-primary">CADASTRAR</button>
                </div></div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

web/templates/clientes/cliente_detail.html
{% extends 'base.html' %}

{% block content %}
{% for field in cliente %}
<br>
<br>
<div class="col-lg-8">
        <div class="card">
                <div class="card-close">
                <a href="{% url 'cliente_edit' field.cpf %}" class="dropdown-item edit"><i class="fa fa-gear"></i></a>
                </div>

                      
                <div class="card-header d-flex align-items-center">
                                <h3 class="h4">Dados Pessoais</h3>
                    </div>
                <div class="card-body">
                    <!-- <div class="avatar"><img src="{{ field.photo.url }}" class="img-fluid rounded-circle" width="200px" height="200px"></div> -->
                    <b>Nome: </b> {{ field.nome }}  <br>
                    <b>CPF: </b> {{ field.cpf }} &nbsp;&nbsp;-&nbsp;&nbsp; <b>RG: </b> {{ field.rg }}  <br>
                    <b>Data de nascimento: </b> {{ field.data_nascimento }}  <br>
                    <b>Sexo: </b> {{ field.sexo }} <br>
                    
                    <hr class="my-3">
                    <b>Residencial: </b> {{ field.tel_fixo }} &nbsp;&nbsp;-&nbsp;&nbsp; <b>Celular: </b> {{ field.tel_cel }} &nbsp;&nbsp;-&nbsp;&nbsp;
                    <b>Emergência: </b> {{ field.tel_emergency }}  &nbsp;&nbsp;-&nbsp;&nbsp; <b>E-mail: </b> {{ field.email }}  <br>

                    <hr class="my-3">
                    <b>Endereço: </b><br>
                    {{ field.logradouro }}, {{ field.numero }} &nbsp; {{ field.complemento }}&nbsp;&nbsp; - &nbsp;&nbsp; {{ field.bairro }} <br>
                    {{ field.cidade }}  &nbsp;-&nbsp; {{ field.uf }}  <br>
                    {{ field.cep }}

                            </div>
                        </div>
                    </div>
{% endfor %}

{% endblock %}

web/templates/clientes/cliente_edit.html
{% extends 'base.html' %}

{% block content %}
<script src="../../static/js/cep.js"></script>
<script src="../../static/js/cpf.js"></script>
<script src="../../static/js/cel.js"></script>
<script src="../../static/js/data.js"></script>
<script src="../../static/js/nome.js"></script>

{% if message.success %}
<div class="alert alert-success" role="alert">
    Um simples alerta success. Olha só!
  </div>
{% endif %}

<br>
<br>
<div class="container-fluid">
  <div class="row">
    <!-- Basic Form-->
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <h3 class="h4">Cadastrar Cliente</h3>
        </div>
        <div class="card-body">
          <p>Os campos com <b>*</b> são de preenchimento obrigatório.</p>
           <!-------------------------------------------------------- DADOS PESSOAIS ------------------------------------------->
           <form name="cliente" method="post">        
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="form-row">

            <div class="form-group col-md-5">
              <label for="id_nome">Nome*</label>
              <input type="text" name="nome" class="form-control" required id="id_nome" value="{{ cliente.nome }}" maxlength="100" onkeyup="capitalize(this.id)">
            </div>
            <div class="form-group col-md-2">      
              <label for="id_nome">CPF*</label>
              <input type="text" name="cpf" class="form-control" required id="id_cpf" value="{{ cliente.cpf }}" readonly=True maxlength="14" onblur="validarCPF(this.value)" oninput="mascara(this)">
              {% if form.cpf.errors %}
              <script>
                  alert('CPF já cadastrado!')
              </script>
              {% endif %}
            </div>

            <div class="form-group col-md-2">
              <label for="id_rg">RG*</label>
              <input type="text" name="rg" class="form-control" required id="id_rg" value="{{ cliente.rg }}" max="20">
            </div>

            <div class="form-group col-md-2">
              <label for="id_data_nascimento">Data de nascimento*</label>
              <input type="text" name="data_nascimento" class="form-control" required id="id_data_nascimento" value="{{ cliente.data_nascimento }}" maxlength="10 " onkeypress="mascaraData(this)">
            </div>

            <div class="form-group col-md-1">
               <label for="id_sexo">Sexo</label>
               <select name="sexo" required id="id_sexo" class="form-control" readonly="true">
                    <option>{{ cliente.sexo }}</option>
                          </select>
            </div>
            <!-- <div class="form-group">
                <label for="id_photo">Foto</label>
                <input type="file" name="photo" class="form-control" id="photo">
                </div> -->
          </div>
                    <!-------------------------------------------------------- FIM DADOS PESSOAIS ------------------------------------------->
                    <hr class="my-3">
                              <!-- ==============================================CONTATOS======================================================= -->
                          <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="id_tel_fixo">Telefone Residencial</label>
                            <input type="text" name="tel_fixo" class="form-control" id="id_tel_fixo" value="{{ cliente.tel_fixo }}" maxlength="15" onkeydown="mask(this, mtel)">
                            </div>

                        <div class="form-group col-md-2">
                            <label for="id_tel_cel">Telefone Celular</label>
                            <input type="text" name="tel_cel" class="form-control" id="id_tel_cel" value="{{ cliente.tel_cel }}" maxlength="15" onkeydown="mask(this, mtel)">
                            </div>
                        <div class="form-group col-md-2">
                            <label for="id_tel_cel">Telefone Emergência</label>
                            <input type="text" name="tel_emergency" class="form-control" id="id_tel_emergency" value="{{ cliente.tel_emergency }}" maxlength="15" onkeydown="mask(this, mtel)">
                            </div> 
                        <div class="form-group col-md-4">
                          <label for="id_email">E-mail</label>
                          <input type="text" name="email" class="form-control" id="email" value="{{ cliente.email }}">
                          </div>
                            </div>
                        
                        <!-------------------------------------------------------- FIM CONTATOS ------------------------------------------->

                        <hr class="my-3">
                          <!-------------------------------------------------------- ENDEREÇO ------------------------------------------->
                          <div class="form-row">
                        <div class="form-group col-md-2">
                          <label for="id_cep">CEP*</label>
                          <input type="text" name="cep" class="form-control" required id="id_cep" value="{{ cliente.cep }}" maxlength="9" onblur="pesquisacep(this.value)">
                        </div>
                        <div class="form-group col-md-6">
                          <label for="id_logradouro">Endereço*</label>
                          <input type="text" name="logradouro" class="form-control" required id="id_logradouro"value="{{ cliente.logradouro }}" maxlength="100">
                        </div>
                        <div class="form-group col-md-1">
                                <label for="id_numero">Número*</label>
                                <input type="text" name="numero" class="form-control" required id="id_numero" value="{{ cliente.numero }}" maxlength="5">
                              </div>
                        <div class="form-group col-md-3">
                            <label for="id_complemento">Complemento</label>
                            <input type="text" name="complemento" class="form-control" id="id_complemento" value="{{ cliente.complemento }}" maxlength="30">
                            </div> 
                      
                          <div class="form-group col-md-4">
                            <label for="id_bairro">Bairro*</label>
                            <input type="text" name="bairro" class="form-control" required id="id_bairro" value="{{ cliente.bairro }}" maxlength="100">
                          </div>     
                        
                          <div class="form-group col-md-4">
                            <label for="id_cidade">Cidade*</label>
                            <input type="text" name="cidade" class="form-control" required id="id_cidade" value="{{ cliente.cidade }}" maxlength="100">
                          </div>
                          <div class="form-group col-md-1">
                                <label for="id_uf">Estado*</label>
                                <input type="text" name="uf" class="form-control" required id="id_uf" value="{{ cliente.uf }}" maxlength="2">
                              </div>
                              
                          <!--------------------------------------------------------FIM DO ENDEREÇO ------------------------------------------->
                        </div>                        
                        <hr class="my-3">
                        <div class="pure-controls">
                                <!-- Início do Modal -->
                                                  <!-- Botão para acionar modal -->
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#salvar_cliente">Salvar</button>
                                
                              <!-- Modal -->
                              <div class="modal fade" id="salvar_cliente" tabindex="-1" role="dialog" aria-labelledby="salvar_alteracoes" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="salvar_alteracoes">Salvar Alterações</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                      Deseja salvar as alterações no cadastro de <b>{{ cliente.nome }}</b>?
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                      <button type="submit" name="salvar" class="btn btn-primary">Sim, salvar</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <!-- Fim do Modal -->               
                              
                              
                              <!-- Início do Modal -->
                                                  <!-- Botão para acionar modal -->
                              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_cliente">Excluir</button>
                                
                                <!-- Modal -->
                                <div class="modal fade" id="del_cliente" tabindex="-1" role="dialog" aria-labelledby="excluir_cliente" aria-hidden="true">
                                  <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="excluir_cliente">Excluir Cadastro</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                      </div>
                                      <div class="modal-body">
                                        Tem certerza que deseja excluir o cadastro de <b>{{ cliente.nome }}</b>? Todos os dados serão perdidos!
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" name="excluir" class="btn btn-danger">Sim, excluir</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <!-- Fim do Modal -->
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

web/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<center>
        <p> 
           <h1>Faculdade Impacta Tecnologia - ADS 4B</h1>    
        </p><br>

	Projeto GC Dominium em desenvolvimento...




</center>
{% endblock %}

web/templates/services/services_cad.html
{% extends 'base.html' %}

{% block content %}
<script src="../../static/js/cep.js"></script>
<script src="../../static/js/cpf.js"></script>
<script src="../../static/js/cel.js"></script>
<script src="../../static/js/data.js"></script>
<script src="../../static/js/nome.js"></script>
<br>
<br>
<div class="container-fluid">
  <div class="row">
    <!-- Basic Form-->
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <h3 class="h4">Cadastrar Serviço</h3>
        </div>
        <div class="card-body">
          <p>Os campos com <b>*</b> são de preenchimento obrigatório.</p>
           <!-------------------------------------------------------- DADOS PESSOAIS ------------------------------------------->
           <form name="service" method="post">        
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="form-row">

            <div class="form-group col-md-5">
              <label for="id_nome">Nome do Serviço*</label>
              <input type="text" name="nome" class="form-control" required id="id_nome" placeholder="Nome completo" maxlength="50" onkeyup="capitalize(this.id)">
            </div>
            <div class="form-group col-md-2">      
              <label for="id_valor">Valor</label>
              <input type="float" name="valor" class="form-control" required id="id_valor" placeholder="R$ 0,00" maxlength="14">
            </div>

            <div class="form-group col-md-9">
              <label for="id_descricao">Descrição</label>
              <textarea name="descricao" class="form-control" rows="12" col="20" required id="id_descricao" placeholder="Fale um pouco sobre este serviço"></textarea>

            </div>
          </div>
                    <!-------------------------------------------------------- FIM DADOS PESSOAIS ------------------------------------------->

                <div class="pure-controls">
                    <button type="submit" class="btn btn-primary">CADASTRAR</button>
                </div></div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

web/templates/services/services_detail.html
{% extends 'base.html' %}

{% block content %}
{% for field in services %}
<br>
<br>
<div class="col-lg-8">
        <div class="card">
                <div class="card-close">
                <a href="{% url 'services_edit' field.id %}" class="dropdown-item edit"><i class="fa fa-gear"></i></a>
                </div>

                      
                <div class="card-header d-flex align-items-center">
                                <h3 class="h4">Dados Pessoais</h3>
                    </div>
                <div class="card-body">
                    <!-- <div class="avatar"><img src="{{ field.photo.url }}" class="img-fluid rounded-circle" width="200px" height="200px"></div> -->
                    <b>Nome: </b> {{ field.nome }}  <br>
                    <b>Valor por sessão: </b> {{ field.valor }} &nbsp;&nbsp;-&nbsp;&nbsp;  <br>
                    <b>Descrição: </b> {{ field.descricao }} <br>
    


                            </div>
                        </div>
                    </div>
{% endfor %}

{% endblock %}